name: check

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
      - name: Install dependencies
        run: mise run ci
      - name: Check
        run: mise run check

  audit:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
      - name: Install dependencies
        run: mise run ci
      - name: Bun audit
        run: mise run audit
        continue-on-error: true
