name: deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  MISE_EXPERIMENTAL: true

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151
      - uses: tailscale/github-action@306e68a486fd2350f2bfc3b19fcd143891a4a2d8
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          audience: ${{ secrets.TS_AUDIENCE }}
          tags: tag:ci
      - name: Deploy
        working-directory: infra
        run: mise run deploy
